Mb/csv reader
ExCALIBUR-NEPTUNE/NESO pull request #185
Opened 2023-06-16 09:34 UTC by mbukaea

# Description

Please include a summary of changes, motivation and context for this PR.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

# Testing

Please describe the tests that you ran to verify your changes and provide instructions for reproducibility. Please also list any relevant details for your test configuration.

- [ ] ReadersTest in test/unit/test_reader.cpp
 - Tests that code can successfully read in charge_exchange_h0_h1.csv in the test_resources folder, by comparing first and last row values compared to those read in.

**Test Configuration**:

* OS: MacOS
* SYCL implementation: hipsycl
* MPI details:
* Hardware: M1 Pro Macbook

# Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have run `clang-format` against my `*.hpp` and `*.cpp` changes
- [ ] I have run `cmake-format` against my changes to `CMakeLists.txt`
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

######### DELETE THIS AND BELOW #########

# How-to:

1. Format C++ source code with clang-format

```
find ./src ./include ./test -iname \*.hpp -o -iname \*.cpp | xargs clang-format -i
```

2. Format cmake files with cmake-format

```
cmake-format -i CMakeLists.txt src/nektar/CMakeLists.txt test/CMakeLists.txt
```

3. Format python with black

```
find ./python -iname \*.py | xargs black
```

2023-06-19 14:13 UTC, jwscook requested changes

2023-06-21 08:46 UTC, oparry-ukaea requested changes

2023-06-21 08:46 UTC, oparry-ukaea commented on test/unit/test_reader.cpp
> +#include "../include/readers.hpp"
I think the name of the header on its own should work here, without "../include/"

2023-06-21 08:46 UTC, oparry-ukaea commented on include/readers.hpp
> +                  << i + 2 << "] to double in file " << m_filepath << std::endl;
After printing the useful info to stderr, I think we should probably rethrow the exception here - having invalid rates data is likely to be a critical error.

```suggestion
        std::cerr << "CSVReader: Invalid argument converting value on line number ["
                  << i + 2 << "] to double in file " << m_filepath << std::endl;
        throw;
```

2023-06-21 08:46 UTC, oparry-ukaea commented on test/unit/test_reader.cpp
> +  ASSERT_NEAR(rates[83], 2.10e-8, 2.11e-8);
If error handling was changed as suggested, could also check for exceptions with invalid data here; something like

```
csv_test_file = test_resources_dir / "bad_charge_exchange_data.csv";
ASSERT_THROW(CSVReader(std::string(csv_test_file)),std::invalid_argument)
```

2023-06-21 08:46 UTC, oparry-ukaea commented on test/unit/test_reader.cpp
> +  ASSERT_NEAR(all_data[0][0], 1.00, 1.01);
Last arg to ASSERT_NEAR should be the tolerance when comparing the first two args for equality. I'd expect the values to be equal to the precision as the string val, so hopefully this should work:
```suggestion
  ASSERT_NEAR(all_data[0][0], 1.0067508210214045, 1e-16);
```

2023-06-21 08:49 UTC, oparry-ukaea commented on include/readers.hpp
> +    for (int i = 0; i < content.size(); i++) {
```suggestion
    for (int i = 0; i < nrows; i++) {
```

2023-06-21 08:51 UTC, mbukaea commented on include/reader_interface_classes.hpp
> +class Reader {
I'll go with AtomicDataReader as the file may not contain a rate

2023-06-21 09:38 UTC, oparry-ukaea commented on include/CSVAtomicReader.hpp
> +      std::vector<std::vector<std::string>> content;
Does it build like this?
I would think `content` would need to be declared before the `if`, since it's referenced on L37

2023-06-21 09:47 UTC, oparry-ukaea commented on test/unit/test_reader.cpp
> +  std::vector<double> temps = CSVReader(std::string(csv_test_file)).GetTemps();
This is creating three objects - better to just create one and call GetData(), GetRates() and GetTemps() on it

2023-06-21 09:57 UTC, oparry-ukaea commented on include/CSVAtomicReader.hpp
> +  CSVReader(std::string filepath) : AtomicDataReader(filepath) { Read(); };
```suggestion
  CSVAtomicReader(std::string filepath) : AtomicDataReader(filepath) { Read(); };
```
Think this is why the declaration of content isn't causing problems - the compiler(s) might actually be ignoring this function altogether

2023-06-21 11:31 UTC, oparry-ukaea commented on test/unit/test_reader.cpp
> +  std::vector<double> temps = CSVAtomicReader(std::string(csv_test_file)).GetTemps();
```suggestion
  CSVAtomicReader atomic_data = CSVAtomicReader(std::string(csv_test_file));
  std::vector<std::vector<double>> all_data = atomic_data.GetData();
  std::vector<double> rates = atomic_data.GetRates();
  std::vector<double> temps = atomic_data.GetTemps();
```

2023-06-21 11:33 UTC, oparry-ukaea commented on include/AtomicDataReader.hpp
> +  std::vector<double> GetTemps() { return m_data[T_idx]; }
Refactor to use snake case for function names, consistent with other NESO headers.
```suggestion
  std::vector<std::vector<double>> get_data() { return m_data; }
  std::vector<double> get_rates() { return m_data[rate_idx]; }
  std::vector<double> get_temps() { return m_data[T_idx]; }
```

2023-06-21 11:53 UTC, oparry-ukaea commented on include/CSVAtomicReader.hpp
> +  CSVAtomicReader(std::string filepath) : AtomicDataReader(filepath) { Read(); };
Think the class name of derived classes should be CSV<base class_name>

2023-06-21 11:54 UTC, oparry-ukaea commented on include/CSVAtomicReader.hpp
> +        std::cerr << "CSVReader: Out-of-double-range argument converting value on line number ["
Update error message to reflect new class name

2023-06-21 11:54 UTC, oparry-ukaea commented on include/CSVAtomicReader.hpp
> +        std::cerr << "CSVReader: Invalid argument converting value on line number ["
Update error message to reflect new class name

2023-06-21 12:02 UTC, oparry-ukaea commented on test/unit/test_reader.cpp
> +  std::vector<double> temps = CSVReader(std::string(csv_test_file)).GetTemps();
Discussion moved to a separate conversation

2023-06-21 12:16 UTC, oparry-ukaea commented on include/AtomicDataReader.hpp
> +  int rate_idx;
```suggestion
  int m_T_idx;
  int m_rate_idx;
```

2023-06-21 12:16 UTC, oparry-ukaea commented on include/AtomicDataReader.hpp
> +  virtual void Read() = 0;
```suggestion
  virtual void read() = 0;
```

2023-06-21 12:17 UTC, oparry-ukaea commented on include/CSVAtomicReader.hpp
> +        // Error handling
Probably don't need this comment

2023-06-21 12:17 UTC, oparry-ukaea commented on include/CSVAtomicReader.hpp
> +        // Error handling
Probably don't need this comment

2023-06-21 13:20 UTC, oparry-ukaea commented on include/readers.hpp
> +          {std::stod(content_file[i][0]), std::stod(content_file[i][1])});
Done

2023-06-21 13:20 UTC, oparry-ukaea commented on include/reader_interface_classes.hpp
> +#ifndef __READER_H__
Done

2023-06-22 10:15 UTC, oparry-ukaea approved these changes

2023-06-22 10:24 UTC, oparry-ukaea commented
All unit and integration tests pass for me with both toolchains on

OS: Ubuntu 22.04
Compiler: GCC 11.3.0 / OneAPI v2022.1.0
SYCL implementation: Hipsycl v0.9.2 / DPC++ v2022.1.0
MPI details: MPICH v4.0.2
Hardware: CPU (Intel Alder Lake)

2023-06-22 10:27 UTC, jwscook approved these changes

2023-06-22 10:28 UTC, merged