3D HW
ExCALIBUR-NEPTUNE/NESO pull request #220
Opened 2023-12-04 12:49 UTC by oparry-ukaea

# Description

Add 3D HW equation system to the H3LAPD solver. 
Resolves #214 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

# Testing

HWTest.3DHWGrowthRates (in test/integration/solvers/H3LAPD/test_H3LAPD.cpp)

Runs the H3LAPD solver with the "HW3DSystem" equation system for a small number of steps with periodic BCs on all sides.
Particle number is set to 0.
Tests that growth rate of enstrophy matches analytical expected rate (see equation 9 in [this ref]).(https://pubs.aip.org/pop/article/6/6/2401/263757/Resistive-drift-wave-turbulence-in-a-three).
Passes iff rate matches to a tolerance of 5e-3 AND the solver returns 0.

N.B. Test of energy growth rate is turned off for now. ([To be reviewed later](#263)).

**Test Configuration**:

OS: Ubuntu 22.04
Compiler: GCC 11.4.0 / OneAPI v2024.1.0
SYCL implementation: Hipsycl v0.9.4 / DPC++ v2024.1.0
MPI details: MPICH v4.0.2 / Intel MPI 2021.8 Build 20221129
Hardware: CPU (Intel Alder Lake)

# Checklist:

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] I have used understandable variable names
- [x] I have run `clang-format` against my `*.hpp` and `*.cpp` changes
- [x] I have run `cmake-format` against my changes to `CMakeLists.txt`
~- [ ] I have made corresponding changes to the documentation~
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

2025-01-07 14:25 UTC, will-saunders-ukaea requested changes
I have gone through and added some comments. I think this PR contains enough Nektar++ solver specifics that an additional look though by someone who understands Nektar++ solvers better than me would be good if possible/suitable (@JamesEdgeley ?).

2025-01-07 14:25 UTC, will-saunders-ukaea commented on solvers/H3LAPD/Diagnostics/GrowthRatesRecorder.hpp
> +      this->phi->PhysDeriv(2, integrand, integrand);
For functions like `PhysDeriv` (and possibly Vmul etc?) I would be careful aliasing the inputs and outputs. Here inarray is a const array and out_d is not a const array hence using the same array for both arguments could cause undefined behavior (?).

[1] https://doc.nektar.info/doxygen/latest/class_nektar_1_1_multi_regions_1_1_exp_list.html#ae1afc120a27ecfa1fb37d692264e37d2

2025-01-07 14:25 UTC, will-saunders-ukaea commented on solvers/H3LAPD/EquationSystems/DriftReducedSystem.cpp
> +                               this->Evec[1], Evec[2]);
```suggestion
                               this->Evec[1], this->Evec[2]);
```

2025-01-07 14:25 UTC, will-saunders-ukaea commented on solvers/H3LAPD/EquationSystems/DriftReducedSystem.cpp
> +    Evec[i] = Array<OneD, NekDouble>(npts);
```suggestion
    this->Evec[i] = Array<OneD, NekDouble>(npts);
```

2025-01-07 15:08 UTC, JamesEdgeley commented on solvers/H3LAPD/EquationSystems/HW2Din3DSystem.cpp
> +   * For some reason this catches NaNs that the check in
This will catch `inf` and `NaN` whereas the Nektar check checks for self-equality so only catches `NaN`  (since `inf==inf` but `NaN!=NaN`)

2025-01-07 15:35 UTC, oparry-ukaea commented on solvers/H3LAPD/EquationSystems/HW2Din3DSystem.cpp
> +   * For some reason this catches NaNs that the check in
Changed the comment and error message accordingly.

2025-01-08 14:33 UTC, oparry-ukaea commented on solvers/H3LAPD/Diagnostics/GrowthRatesRecorder.hpp
> +      this->fh.open("growth_rates.csv");
Moved generic_hdf5_writer.hpp as discussed and modified generic_hdf5_writer.hpp to use it.

2025-01-08 14:41 UTC, oparry-ukaea commented on solvers/H3LAPD/Diagnostics/GrowthRatesRecorder.hpp
> +      this->phi->PhysDeriv(2, integrand, integrand);
Thanks, good point.
I've modified GrowthRatesRecorder to use temporary arrays instead for all Vmath and PhysDeriv calls.
Also created [this issue](https://github.com/ExCALIBUR-NEPTUNE/NESO/issues/278) to check the rest of the code - I've almost certainly used this shortcut elsewhere.

2025-01-08 15:10 UTC, will-saunders-ukaea commented
Tests pass for neso%gcc and neso%oneapi without new errors (I do see https://github.com/ExCALIBUR-NEPTUNE/NESO/issues/267 still).

2025-01-08 15:11 UTC, will-saunders-ukaea approved these changes

2025-01-08 15:19 UTC, merged