Temp hack to get around issue of linking to Nektar++ Solver libraries
ExCALIBUR-NEPTUNE/NESO pull request #257
Opened 2024-10-17 12:15 UTC by seimtpow

Linking to solver libraries that register enums for their solvers mean that every eqtype has to have a enum registered. 

Should be considered a temporary fix - Will open issue with full description of problem for consideration

2024-10-17 14:26 UTC, oparry-ukaea requested changes
Tested by building nektar via spack with +compflow_solver+pulsewave_solver then
`...integrationTests --gtest_filter=HW*:SimpleSOL*`

Equation system label for the 2Din3D HW system needs changing; all good otherwise.

2024-10-17 14:26 UTC, oparry-ukaea commented on solvers/H3LAPD/EquationSystems/HW2Din3DSystem.cpp
> + Nektar::LibUtilities::SessionReader::RegisterEnumValue("EqType", "HW2Din3D",enumHW2Din3DSystem);
Unhelpfully, I chose a label that's not consistent with the class name, so this needs to be:
```suggestion
 Nektar::LibUtilities::SessionReader::RegisterEnumValue("EqType", "2Din3DHW",enumHW2Din3DSystem);
```

2024-10-17 15:56 UTC, seimtpow commented
Sorry I don't think this fixes the unit tests. The "Test" EqType throws an error - I need to register that too.

2024-10-21 10:40 UTC, oparry-ukaea commented
I don't think "Test" actually corresponds to a real equation system, suspect it was just put in to indicate that no nektar equation system is needed.  Is that right @will-saunders-ukaea ?

The integration tests pass for me if I
- remove all of the `<I PROPERTY="EQTYPE" VALUE="Test" />` nodes (10 files)
- remove `<I PROPERTY="EQTYPE" VALUE="UnsteadyDiffusion" />` from test/test_resources/MASTU-2D/conditions_nummodes_2.xml, which doesn't seem to be required.

2024-10-21 10:57 UTC, will-saunders-ukaea commented
Yes I think you are right. I don't think I use an equation system anywhere. I cannot remember if I needed that block to exist or if I was simply following a config that seemed to work.

If removing them solves issues then go for it.

2024-10-21 11:05 UTC, oparry-ukaea commented
:+1: thanks for confirming

2024-11-22 17:25 UTC, seimtpow commented
Going to close this as had to apply fixes (+ fixed unit tests)  in  https://github.com/ExCALIBUR-NEPTUNE/NESO/pull/259 in order to test.

2024-11-22 17:25 UTC, closed without merging