WIP: Set up spack environment to handle build
ExCALIBUR-NEPTUNE/NESO pull request #93
Opened 2022-09-16 11:55 UTC by cmacmackin

# Description

The current build instructions are a bit ad-hoc. I have attempted to make the build process more robust using Spack. In particular, I have added a `spack.yaml` file which defines a custom [Spack environment](https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html) to be [used for development](https://spack-tutorial.readthedocs.io/en/latest/tutorial_developer_workflows.html). 

Addressed (at least partially) #3, #20, relates to #86.

## Type of change

- [ ] Build system improvements
- [ ] Requires documentation updates

# Testing

The build was executed and confirmed to work on my laptop. The resulting test binaries which were built were run and all passed.

**Test Configuration**:

* OS: Linux Mint 21 (Ubuntu 22.04)
* SYCL implementation: HipSYCL 0.9.2
* MPI details: MPICH 4.0.2
* Hardware: Intel Icelake

# Checklist:

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any new dependencies are automatically built for users via `cmake`
- [ ] I have used understandable variable names
- [ ] I have run `clang-format` against my `*.hpp` and `*.cpp` changes
- [ ] I have run `cmake-format` against my changes to `CMakeLists.txt`
- [ ] I have run `black` against changes to `*.py`
- [ ] I have made corresponding changes to the documentation
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings

2022-10-17 15:36 UTC, cmacmackin commented
@jwscook @will-saunders-ukaea This is in a state I'm reasonably happy with. It is ready for review and can be merged after NESO-Spack#3.

2022-10-19 15:34 UTC, jwscook requested changes
... now you can see my comments...

2022-10-19 15:39 UTC, cmacmackin commented on CMakeLists.txt
> +  message("REGEX evaluated true")
Oh, that should just be removed, actually. It was just in there for debugging purposes.

2022-10-19 15:46 UTC, cmacmackin commented on spack.yaml
> +  - neso%gcc ^openblas
I think this diff is out of date (not sure how the interface allowed that to happen). If you check the files changed tab now you'll see that `^hipsycl` is there.

2022-10-19 15:46 UTC, cmacmackin commented on README.md
>  The test suite requires the [Boost library](https://www.boost.org/) (version >= 1.78).
Updated (along with the dependency in the NESO package).

2022-10-21 11:55 UTC, merged